PROJECT_ID = 'cs-385-cloudpay'
DATA_BACKEND = 'cloudsql'
CLOUDSQL_USER = 'root'
CLOUDSQL_PASSWORD = 'cs385'
CLOUDSQL_DATABASE = 'timesheets'
CLOUDSQL_CONNECTION_NAME = 'cs-385-cloudpay:us-west1:timesheets'
